// Generated by CoffeeScript 1.6.3
var reloadjs;

reloadjs = function(reload_time, url) {
  var reload;
  if (reload_time == null) {
    reload_time = 5;
  }
  if (url == null) {
    url = null;
  }
  reload = function() {
    if (url) {
      return window.location(url);
    } else {
      return window.location.reload();
    }
  };
  return setInterval(reload, reload_time * 1000);
};
