// Generated by CoffeeScript 1.6.3
var reloadjs;

reloadjs = function(reload_time, key_ctrl, url) {
  var interval, keyfunc, reload, startInterval, stopInterval,
    _this = this;
  if (reload_time == null) {
    reload_time = 5;
  }
  if (key_ctrl == null) {
    key_ctrl = false;
  }
  if (url == null) {
    url = null;
  }
  reload = function() {
    if (url) {
      return window.location(url);
    } else {
      return window.location.reload();
    }
  };
  startInterval = function() {
    if (!_this.interval) {
      return _this.interval = setInterval(reload, reload_time * 1000);
    }
  };
  stopInterval = function() {
    if (_this.interval !== null) {
      clearInterval(_this.interval);
      return _this.interval = null;
    }
  };
  keyfunc = function() {
    var e, input;
    if (!e) {
      e = window.event;
    }
    input = e.keyCode;
    if (input === 80) {
      return stopInterval();
    } else if (input === 83) {
      return startInterval();
    }
  };
  interval = null;
  startInterval();
  if (key_ctrl) {
    if (document.addEventListener) {
      return document.addEventListener("keyup", keyfunc);
    } else if (document.attachEvent) {
      return document.attachEvent("onkeyup", keyfunc);
    }
  }
};
